{{- if and .Values.ingress.enabled (eq (include "web-app.ingressType" .) "ingress") }}
{{- $host := include "web-app.ingressHost" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ include "web-app.tlsSecretName" . }}
      hosts:
        - {{ $host | quote }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "web-app.fullname" . }}
                port:
                  name: http
{{- end }}
